export enum PAYOUT_STATUS {
	UNMATCHED = "UNMATCHED",
	MATCHED = "MATCHED",
	FLAGGED = "FLAGGED",
}

export enum WITHDRAWAL_STATUS {
	PENDING = "PENDING",
	MATCHED = "MATCHED",
	FLAGGED = "FLAGGED",
	MISSING = "MISSING",
}
